### ISSUE TITLE
Link in README is broken

### ISSUE THREAD

**Issue by akriegman** [rtavenner/Uniform-Polychora#1]
Hey, I went to share this project with someone today but the link in the readme is broken. I think it's just because Github moved their HTML preview thing to github.io. This link should work: https://htmlpreview.github.io/?https://github.com/rtavenner/Uniform-Polychora/master/index.html

**Comment by rtavenner** [comment]
Thanks for telling me! It turns out this was an issue with my other projects as well, so I fixed them all.
